name: Pull Request
on: [pull_request]

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        run: yarn lint
      - name: Run Prettier check
        run: yarn prettier
  deploy-to-playground:
    needs: lint-and-prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          deploy-message: ${{ github.event.pull_request.title }}
          enable-pull-request-comment: true
          functions-dir: 'functions'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-config-path: ./netlify.toml
          publish-dir: 'build'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
